import {useEffect, useRef, useState} from "react";
import {useWS} from "./useWS.ts";

/**
 * Subscribes to the LiDAR dock-match telemetry topics surfaced by Plan 02-04
 * (mowgli_lidar_docking::DockScanMatchNode):
 *   - /dock_match/pose       (geometry_msgs/PoseWithCovarianceStamped, reliable depth=1)
 *   - /dock_match/confidence (mowgli_interfaces/DockMatchConfidence, SensorDataQoS, ~10 Hz)
 *
 * The Go backend's topicMap (gui/pkg/providers/ros.go) relays both topics under
 * the logical keys "dockMatchPose" and "dockMatchConfidence" — see also
 * gui/pkg/api/mowglinext.go SubscriberRoute. D-12 reconciliation locked the
 * Go-relay topicMap pattern (mirrors useMagYaw / useDockingSensor); we do NOT
 * spin up a parallel browser-side rosbridge connection.
 *
 * The DockMatchConfidence type is auto-generated by Plan 02-01 codegen into
 * gui/web/src/types/ros.generated.ts. It is intentionally redeclared here as
 * an inline type — gui/web/src/types/ros.ts is hand-curated and has not yet
 * been resynced from ros.generated.ts; we avoid hand-editing either.
 */
export type DockMatchConfidence = {
    header?: { stamp: { sec: number; nanosec: number }; frame_id: string };
    inlier_ratio?: number;
    rmse_m?: number;
    trusted?: boolean;
};

export type DockMatchPose = {
    header?: { stamp: { sec: number; nanosec: number }; frame_id: string };
    pose?: {
        pose?: {
            position?: { x: number; y: number; z: number };
            orientation?: { x: number; y: number; z: number; w: number };
        };
        covariance?: number[];
    };
};

export const useDockMatch = (): {
    pose: DockMatchPose | null;
    confidence: DockMatchConfidence | null;
    lastMessageAt: number | null;
} => {
    const [pose, setPose] = useState<DockMatchPose | null>(null);
    const [confidence, setConfidence] = useState<DockMatchConfidence | null>(null);
    const lastRef = useRef<number | null>(null);
    const [lastMessageAt, setLastMessageAt] = useState<number | null>(null);

    const poseStream = useWS<string>(
        () => { console.log({message: "DockMatchPose Stream closed"}); },
        () => { console.log({message: "DockMatchPose Stream connected"}); },
        (e) => {
            try {
                setPose(JSON.parse(e) as DockMatchPose);
            } catch (err) {
                console.warn("useDockMatch: failed to parse pose payload", err);
            }
        }
    );

    const confStream = useWS<string>(
        () => { console.log({message: "DockMatchConfidence Stream closed"}); },
        () => { console.log({message: "DockMatchConfidence Stream connected"}); },
        (e) => {
            try {
                setConfidence(JSON.parse(e) as DockMatchConfidence);
                const now = Date.now();
                lastRef.current = now;
                setLastMessageAt(now);
            } catch (err) {
                console.warn("useDockMatch: failed to parse confidence payload", err);
            }
        }
    );

    useEffect(() => {
        poseStream.start("/api/mowglinext/subscribe/dockMatchPose");
        confStream.start("/api/mowglinext/subscribe/dockMatchConfidence");
        return () => {
            poseStream.stop();
            confStream.stop();
        };
    }, []);

    return {pose, confidence, lastMessageAt};
};
