#ifndef _ROS_mower_msgs_CalibrateImuYawStatus_h
#define _ROS_mower_msgs_CalibrateImuYawStatus_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class CalibrateImuYawStatus : public ros::Msg
  {
    public:
      typedef const char* _job_id_type;
      _job_id_type job_id;
      typedef bool _done_type;
      _done_type done;
      typedef bool _success_type;
      _success_type success;
      typedef const char* _message_type;
      _message_type message;
      typedef double _imu_yaw_rad_type;
      _imu_yaw_rad_type imu_yaw_rad;
      typedef double _imu_yaw_deg_type;
      _imu_yaw_deg_type imu_yaw_deg;
      typedef int32_t _samples_used_type;
      _samples_used_type samples_used;
      typedef double _std_dev_deg_type;
      _std_dev_deg_type std_dev_deg;
      typedef double _imu_pitch_rad_type;
      _imu_pitch_rad_type imu_pitch_rad;
      typedef double _imu_pitch_deg_type;
      _imu_pitch_deg_type imu_pitch_deg;
      typedef double _imu_roll_rad_type;
      _imu_roll_rad_type imu_roll_rad;
      typedef double _imu_roll_deg_type;
      _imu_roll_deg_type imu_roll_deg;
      typedef int32_t _stationary_samples_used_type;
      _stationary_samples_used_type stationary_samples_used;
      typedef double _gravity_mag_mps2_type;
      _gravity_mag_mps2_type gravity_mag_mps2;

    CalibrateImuYawStatus():
      job_id(""),
      done(0),
      success(0),
      message(""),
      imu_yaw_rad(0),
      imu_yaw_deg(0),
      samples_used(0),
      std_dev_deg(0),
      imu_pitch_rad(0),
      imu_pitch_deg(0),
      imu_roll_rad(0),
      imu_roll_deg(0),
      stationary_samples_used(0),
      gravity_mag_mps2(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      uint32_t length_job_id = strlen(this->job_id);
      varToArr(outbuffer + offset, length_job_id);
      offset += 4;
      memcpy(outbuffer + offset, this->job_id, length_job_id);
      offset += length_job_id;
      union {
        bool real;
        uint8_t base;
      } u_done;
      u_done.real = this->done;
      *(outbuffer + offset + 0) = (u_done.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->done);
      union {
        bool real;
        uint8_t base;
      } u_success;
      u_success.real = this->success;
      *(outbuffer + offset + 0) = (u_success.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->success);
      uint32_t length_message = strlen(this->message);
      varToArr(outbuffer + offset, length_message);
      offset += 4;
      memcpy(outbuffer + offset, this->message, length_message);
      offset += length_message;
      union {
        double real;
        uint64_t base;
      } u_imu_yaw_rad;
      u_imu_yaw_rad.real = this->imu_yaw_rad;
      *(outbuffer + offset + 0) = (u_imu_yaw_rad.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_yaw_rad.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_yaw_rad.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_yaw_rad.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_yaw_rad.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_yaw_rad.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_yaw_rad.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_yaw_rad.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_yaw_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_yaw_deg;
      u_imu_yaw_deg.real = this->imu_yaw_deg;
      *(outbuffer + offset + 0) = (u_imu_yaw_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_yaw_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_yaw_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_yaw_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_yaw_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_yaw_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_yaw_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_yaw_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_yaw_deg);
      union {
        int32_t real;
        uint32_t base;
      } u_samples_used;
      u_samples_used.real = this->samples_used;
      *(outbuffer + offset + 0) = (u_samples_used.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_samples_used.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_samples_used.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_samples_used.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->samples_used);
      union {
        double real;
        uint64_t base;
      } u_std_dev_deg;
      u_std_dev_deg.real = this->std_dev_deg;
      *(outbuffer + offset + 0) = (u_std_dev_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_std_dev_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_std_dev_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_std_dev_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_std_dev_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_std_dev_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_std_dev_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_std_dev_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->std_dev_deg);
      union {
        double real;
        uint64_t base;
      } u_imu_pitch_rad;
      u_imu_pitch_rad.real = this->imu_pitch_rad;
      *(outbuffer + offset + 0) = (u_imu_pitch_rad.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_pitch_rad.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_pitch_rad.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_pitch_rad.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_pitch_rad.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_pitch_rad.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_pitch_rad.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_pitch_rad.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_pitch_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_pitch_deg;
      u_imu_pitch_deg.real = this->imu_pitch_deg;
      *(outbuffer + offset + 0) = (u_imu_pitch_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_pitch_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_pitch_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_pitch_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_pitch_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_pitch_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_pitch_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_pitch_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_pitch_deg);
      union {
        double real;
        uint64_t base;
      } u_imu_roll_rad;
      u_imu_roll_rad.real = this->imu_roll_rad;
      *(outbuffer + offset + 0) = (u_imu_roll_rad.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_roll_rad.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_roll_rad.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_roll_rad.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_roll_rad.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_roll_rad.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_roll_rad.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_roll_rad.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_roll_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_roll_deg;
      u_imu_roll_deg.real = this->imu_roll_deg;
      *(outbuffer + offset + 0) = (u_imu_roll_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_imu_roll_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_imu_roll_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_imu_roll_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_imu_roll_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_imu_roll_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_imu_roll_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_imu_roll_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->imu_roll_deg);
      union {
        int32_t real;
        uint32_t base;
      } u_stationary_samples_used;
      u_stationary_samples_used.real = this->stationary_samples_used;
      *(outbuffer + offset + 0) = (u_stationary_samples_used.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_stationary_samples_used.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_stationary_samples_used.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_stationary_samples_used.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->stationary_samples_used);
      union {
        double real;
        uint64_t base;
      } u_gravity_mag_mps2;
      u_gravity_mag_mps2.real = this->gravity_mag_mps2;
      *(outbuffer + offset + 0) = (u_gravity_mag_mps2.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_gravity_mag_mps2.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_gravity_mag_mps2.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_gravity_mag_mps2.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_gravity_mag_mps2.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_gravity_mag_mps2.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_gravity_mag_mps2.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_gravity_mag_mps2.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->gravity_mag_mps2);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      uint32_t length_job_id;
      arrToVar(length_job_id, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_job_id; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_job_id-1]=0;
      this->job_id = (char *)(inbuffer + offset-1);
      offset += length_job_id;
      union {
        bool real;
        uint8_t base;
      } u_done;
      u_done.base = 0;
      u_done.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->done = u_done.real;
      offset += sizeof(this->done);
      union {
        bool real;
        uint8_t base;
      } u_success;
      u_success.base = 0;
      u_success.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->success = u_success.real;
      offset += sizeof(this->success);
      uint32_t length_message;
      arrToVar(length_message, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_message; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_message-1]=0;
      this->message = (char *)(inbuffer + offset-1);
      offset += length_message;
      union {
        double real;
        uint64_t base;
      } u_imu_yaw_rad;
      u_imu_yaw_rad.base = 0;
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_yaw_rad.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_yaw_rad = u_imu_yaw_rad.real;
      offset += sizeof(this->imu_yaw_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_yaw_deg;
      u_imu_yaw_deg.base = 0;
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_yaw_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_yaw_deg = u_imu_yaw_deg.real;
      offset += sizeof(this->imu_yaw_deg);
      union {
        int32_t real;
        uint32_t base;
      } u_samples_used;
      u_samples_used.base = 0;
      u_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->samples_used = u_samples_used.real;
      offset += sizeof(this->samples_used);
      union {
        double real;
        uint64_t base;
      } u_std_dev_deg;
      u_std_dev_deg.base = 0;
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_std_dev_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->std_dev_deg = u_std_dev_deg.real;
      offset += sizeof(this->std_dev_deg);
      union {
        double real;
        uint64_t base;
      } u_imu_pitch_rad;
      u_imu_pitch_rad.base = 0;
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_pitch_rad.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_pitch_rad = u_imu_pitch_rad.real;
      offset += sizeof(this->imu_pitch_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_pitch_deg;
      u_imu_pitch_deg.base = 0;
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_pitch_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_pitch_deg = u_imu_pitch_deg.real;
      offset += sizeof(this->imu_pitch_deg);
      union {
        double real;
        uint64_t base;
      } u_imu_roll_rad;
      u_imu_roll_rad.base = 0;
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_roll_rad.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_roll_rad = u_imu_roll_rad.real;
      offset += sizeof(this->imu_roll_rad);
      union {
        double real;
        uint64_t base;
      } u_imu_roll_deg;
      u_imu_roll_deg.base = 0;
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_imu_roll_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->imu_roll_deg = u_imu_roll_deg.real;
      offset += sizeof(this->imu_roll_deg);
      union {
        int32_t real;
        uint32_t base;
      } u_stationary_samples_used;
      u_stationary_samples_used.base = 0;
      u_stationary_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_stationary_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_stationary_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_stationary_samples_used.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->stationary_samples_used = u_stationary_samples_used.real;
      offset += sizeof(this->stationary_samples_used);
      union {
        double real;
        uint64_t base;
      } u_gravity_mag_mps2;
      u_gravity_mag_mps2.base = 0;
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_gravity_mag_mps2.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->gravity_mag_mps2 = u_gravity_mag_mps2.real;
      offset += sizeof(this->gravity_mag_mps2);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/CalibrateImuYawStatus"; };
    virtual const char * getMD5() override { return "9cafc2f26b5f0d0ffe392c3b685e2f43"; };

  };

}
#endif
