#ifndef _ROS_mower_msgs_Checkpoint_h
#define _ROS_mower_msgs_Checkpoint_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Pose.h"

namespace mower_msgs
{

  class Checkpoint : public ros::Msg
  {
    public:
      typedef uint32_t _area_index_type;
      _area_index_type area_index;
      typedef uint32_t _current_outline_index_type;
      _current_outline_index_type current_outline_index;
      typedef uint32_t _current_swath_index_type;
      _current_swath_index_type current_swath_index;
      typedef uint8_t _swath_direction_type;
      _swath_direction_type swath_direction;
      typedef uint32_t _last_completed_swath_index_type;
      _last_completed_swath_index_type last_completed_swath_index;
      typedef uint32_t _next_open_swath_index_type;
      _next_open_swath_index_type next_open_swath_index;
      typedef double _last_mow_angle_deg_type;
      _last_mow_angle_deg_type last_mow_angle_deg;
      typedef geometry_msgs::Pose _last_swath_endpoint_type;
      _last_swath_endpoint_type last_swath_endpoint;
      enum { SWATH_DIRECTION_FORWARD = 0 };
      enum { SWATH_DIRECTION_REVERSE = 1 };

    Checkpoint():
      area_index(0),
      current_outline_index(0),
      current_swath_index(0),
      swath_direction(0),
      last_completed_swath_index(0),
      next_open_swath_index(0),
      last_mow_angle_deg(0),
      last_swath_endpoint()
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        uint32_t real;
        uint32_t base;
      } u_area_index;
      u_area_index.real = this->area_index;
      *(outbuffer + offset + 0) = (u_area_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_area_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_area_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_area_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->area_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_current_outline_index;
      u_current_outline_index.real = this->current_outline_index;
      *(outbuffer + offset + 0) = (u_current_outline_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_current_outline_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_current_outline_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_current_outline_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->current_outline_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_current_swath_index;
      u_current_swath_index.real = this->current_swath_index;
      *(outbuffer + offset + 0) = (u_current_swath_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_current_swath_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_current_swath_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_current_swath_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->current_swath_index);
      *(outbuffer + offset + 0) = (this->swath_direction >> (8 * 0)) & 0xFF;
      offset += sizeof(this->swath_direction);
      union {
        uint32_t real;
        uint32_t base;
      } u_last_completed_swath_index;
      u_last_completed_swath_index.real = this->last_completed_swath_index;
      *(outbuffer + offset + 0) = (u_last_completed_swath_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_last_completed_swath_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_last_completed_swath_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_last_completed_swath_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->last_completed_swath_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_next_open_swath_index;
      u_next_open_swath_index.real = this->next_open_swath_index;
      *(outbuffer + offset + 0) = (u_next_open_swath_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_next_open_swath_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_next_open_swath_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_next_open_swath_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->next_open_swath_index);
      union {
        double real;
        uint64_t base;
      } u_last_mow_angle_deg;
      u_last_mow_angle_deg.real = this->last_mow_angle_deg;
      *(outbuffer + offset + 0) = (u_last_mow_angle_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_last_mow_angle_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_last_mow_angle_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_last_mow_angle_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_last_mow_angle_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_last_mow_angle_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_last_mow_angle_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_last_mow_angle_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->last_mow_angle_deg);
      offset += this->last_swath_endpoint.serialize(outbuffer + offset);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        uint32_t real;
        uint32_t base;
      } u_area_index;
      u_area_index.base = 0;
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->area_index = u_area_index.real;
      offset += sizeof(this->area_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_current_outline_index;
      u_current_outline_index.base = 0;
      u_current_outline_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_current_outline_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_current_outline_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_current_outline_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->current_outline_index = u_current_outline_index.real;
      offset += sizeof(this->current_outline_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_current_swath_index;
      u_current_swath_index.base = 0;
      u_current_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_current_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_current_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_current_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->current_swath_index = u_current_swath_index.real;
      offset += sizeof(this->current_swath_index);
      this->swath_direction =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->swath_direction);
      union {
        uint32_t real;
        uint32_t base;
      } u_last_completed_swath_index;
      u_last_completed_swath_index.base = 0;
      u_last_completed_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_last_completed_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_last_completed_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_last_completed_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->last_completed_swath_index = u_last_completed_swath_index.real;
      offset += sizeof(this->last_completed_swath_index);
      union {
        uint32_t real;
        uint32_t base;
      } u_next_open_swath_index;
      u_next_open_swath_index.base = 0;
      u_next_open_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_next_open_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_next_open_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_next_open_swath_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->next_open_swath_index = u_next_open_swath_index.real;
      offset += sizeof(this->next_open_swath_index);
      union {
        double real;
        uint64_t base;
      } u_last_mow_angle_deg;
      u_last_mow_angle_deg.base = 0;
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_last_mow_angle_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->last_mow_angle_deg = u_last_mow_angle_deg.real;
      offset += sizeof(this->last_mow_angle_deg);
      offset += this->last_swath_endpoint.deserialize(inbuffer + offset);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/Checkpoint"; };
    virtual const char * getMD5() override { return "4bab6b88f21e589f7fd353cada5e08f7"; };

  };

}
#endif
