#ifndef _ROS_mower_msgs_CoverageWaypoint_h
#define _ROS_mower_msgs_CoverageWaypoint_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/PoseStamped.h"

namespace mower_msgs
{

  class CoverageWaypoint : public ros::Msg
  {
    public:
      typedef geometry_msgs::PoseStamped _pose_type;
      _pose_type pose;
      typedef uint32_t _sequence_id_type;
      _sequence_id_type sequence_id;
      typedef uint32_t _area_index_type;
      _area_index_type area_index;
      typedef float _speed_type;
      _speed_type speed;
      typedef bool _blade_enabled_type;
      _blade_enabled_type blade_enabled;
      typedef uint8_t _segment_type_type;
      _segment_type_type segment_type;
      enum { SEGMENT_UNDOCK = 0 };
      enum { SEGMENT_TRANSIT = 1 };
      enum { SEGMENT_OUTLINE_WORKING_AREA = 2 };
      enum { SEGMENT_OUTLINE_OBSTACLE = 3 };
      enum { SEGMENT_MOWING_BOUSTROPHEDON = 4 };
      enum { SEGMENT_RETURN_TO_DOCK = 5 };
      enum { SEGMENT_DOCK_APPROACH = 6 };
      enum { SEGMENT_DOCKING = 7 };

    CoverageWaypoint():
      pose(),
      sequence_id(0),
      area_index(0),
      speed(0),
      blade_enabled(0),
      segment_type(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->pose.serialize(outbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_sequence_id;
      u_sequence_id.real = this->sequence_id;
      *(outbuffer + offset + 0) = (u_sequence_id.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_sequence_id.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_sequence_id.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_sequence_id.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->sequence_id);
      union {
        uint32_t real;
        uint32_t base;
      } u_area_index;
      u_area_index.real = this->area_index;
      *(outbuffer + offset + 0) = (u_area_index.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_area_index.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_area_index.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_area_index.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->area_index);
      union {
        float real;
        uint32_t base;
      } u_speed;
      u_speed.real = this->speed;
      *(outbuffer + offset + 0) = (u_speed.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_speed.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_speed.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_speed.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->speed);
      union {
        bool real;
        uint8_t base;
      } u_blade_enabled;
      u_blade_enabled.real = this->blade_enabled;
      *(outbuffer + offset + 0) = (u_blade_enabled.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->blade_enabled);
      *(outbuffer + offset + 0) = (this->segment_type >> (8 * 0)) & 0xFF;
      offset += sizeof(this->segment_type);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->pose.deserialize(inbuffer + offset);
      union {
        uint32_t real;
        uint32_t base;
      } u_sequence_id;
      u_sequence_id.base = 0;
      u_sequence_id.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_sequence_id.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_sequence_id.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_sequence_id.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->sequence_id = u_sequence_id.real;
      offset += sizeof(this->sequence_id);
      union {
        uint32_t real;
        uint32_t base;
      } u_area_index;
      u_area_index.base = 0;
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_area_index.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->area_index = u_area_index.real;
      offset += sizeof(this->area_index);
      union {
        float real;
        uint32_t base;
      } u_speed;
      u_speed.base = 0;
      u_speed.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_speed.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_speed.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_speed.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->speed = u_speed.real;
      offset += sizeof(this->speed);
      union {
        bool real;
        uint8_t base;
      } u_blade_enabled;
      u_blade_enabled.base = 0;
      u_blade_enabled.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->blade_enabled = u_blade_enabled.real;
      offset += sizeof(this->blade_enabled);
      this->segment_type =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->segment_type);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/CoverageWaypoint"; };
    virtual const char * getMD5() override { return "cc3dbf146086f3b6a188c6b3796bceec"; };

  };

}
#endif
