#ifndef _ROS_mower_msgs_DockMatchConfidence_h
#define _ROS_mower_msgs_DockMatchConfidence_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class DockMatchConfidence : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      typedef float _inlier_ratio_type;
      _inlier_ratio_type inlier_ratio;
      typedef float _rmse_m_type;
      _rmse_m_type rmse_m;
      typedef bool _trusted_type;
      _trusted_type trusted;

    DockMatchConfidence():
      header(),
      inlier_ratio(0),
      rmse_m(0),
      trusted(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      union {
        float real;
        uint32_t base;
      } u_inlier_ratio;
      u_inlier_ratio.real = this->inlier_ratio;
      *(outbuffer + offset + 0) = (u_inlier_ratio.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_inlier_ratio.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_inlier_ratio.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_inlier_ratio.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->inlier_ratio);
      union {
        float real;
        uint32_t base;
      } u_rmse_m;
      u_rmse_m.real = this->rmse_m;
      *(outbuffer + offset + 0) = (u_rmse_m.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_rmse_m.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_rmse_m.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_rmse_m.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->rmse_m);
      union {
        bool real;
        uint8_t base;
      } u_trusted;
      u_trusted.real = this->trusted;
      *(outbuffer + offset + 0) = (u_trusted.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->trusted);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      union {
        float real;
        uint32_t base;
      } u_inlier_ratio;
      u_inlier_ratio.base = 0;
      u_inlier_ratio.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_inlier_ratio.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_inlier_ratio.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_inlier_ratio.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->inlier_ratio = u_inlier_ratio.real;
      offset += sizeof(this->inlier_ratio);
      union {
        float real;
        uint32_t base;
      } u_rmse_m;
      u_rmse_m.base = 0;
      u_rmse_m.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_rmse_m.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_rmse_m.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_rmse_m.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->rmse_m = u_rmse_m.real;
      offset += sizeof(this->rmse_m);
      union {
        bool real;
        uint8_t base;
      } u_trusted;
      u_trusted.base = 0;
      u_trusted.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->trusted = u_trusted.real;
      offset += sizeof(this->trusted);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/DockMatchConfidence"; };
    virtual const char * getMD5() override { return "b91245504e7ecbfed8dca728fbe99816"; };

  };

}
#endif
