#ifndef _ROS_mower_msgs_MapArea_h
#define _ROS_mower_msgs_MapArea_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Polygon.h"

namespace mower_msgs
{

  class MapArea : public ros::Msg
  {
    public:
      typedef const char* _name_type;
      _name_type name;
      typedef geometry_msgs::Polygon _area_type;
      _area_type area;
      uint32_t obstacles_length;
      typedef geometry_msgs::Polygon _obstacles_type;
      _obstacles_type st_obstacles;
      _obstacles_type * obstacles;
      typedef bool _is_navigation_area_type;
      _is_navigation_area_type is_navigation_area;
      typedef uint8_t _narrow_area_strategy_type;
      _narrow_area_strategy_type narrow_area_strategy;

    MapArea():
      name(""),
      area(),
      obstacles_length(0), st_obstacles(), obstacles(nullptr),
      is_navigation_area(0),
      narrow_area_strategy(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      uint32_t length_name = strlen(this->name);
      varToArr(outbuffer + offset, length_name);
      offset += 4;
      memcpy(outbuffer + offset, this->name, length_name);
      offset += length_name;
      offset += this->area.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->obstacles_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->obstacles_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->obstacles_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->obstacles_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->obstacles_length);
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].serialize(outbuffer + offset);
      }
      union {
        bool real;
        uint8_t base;
      } u_is_navigation_area;
      u_is_navigation_area.real = this->is_navigation_area;
      *(outbuffer + offset + 0) = (u_is_navigation_area.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->is_navigation_area);
      *(outbuffer + offset + 0) = (this->narrow_area_strategy >> (8 * 0)) & 0xFF;
      offset += sizeof(this->narrow_area_strategy);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      uint32_t length_name;
      arrToVar(length_name, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_name; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_name-1]=0;
      this->name = (char *)(inbuffer + offset-1);
      offset += length_name;
      offset += this->area.deserialize(inbuffer + offset);
      uint32_t obstacles_lengthT = ((uint32_t) (*(inbuffer + offset)));
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      obstacles_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->obstacles_length);
      if(obstacles_lengthT > obstacles_length)
        this->obstacles = (geometry_msgs::Polygon*)realloc(this->obstacles, obstacles_lengthT * sizeof(geometry_msgs::Polygon));
      obstacles_length = obstacles_lengthT;
      for( uint32_t i = 0; i < obstacles_length; i++){
        offset += this->obstacles[i].deserialize(inbuffer + offset);
      }
      union {
        bool real;
        uint8_t base;
      } u_is_navigation_area;
      u_is_navigation_area.base = 0;
      u_is_navigation_area.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->is_navigation_area = u_is_navigation_area.real;
      offset += sizeof(this->is_navigation_area);
      this->narrow_area_strategy =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->narrow_area_strategy);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/MapArea"; };
    virtual const char * getMD5() override { return "95c4cd71205ce55b6d40a3234589b32a"; };

  };

}
#endif
