#ifndef _ROS_mower_msgs_PlanningParams_h
#define _ROS_mower_msgs_PlanningParams_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"

namespace mower_msgs
{

  class PlanningParams : public ros::Msg
  {
    public:
      typedef double _outline_passes_type;
      _outline_passes_type outline_passes;
      typedef double _outline_offset_type;
      _outline_offset_type outline_offset;
      typedef double _outline_overlap_type;
      _outline_overlap_type outline_overlap;
      typedef double _path_spacing_type;
      _path_spacing_type path_spacing;
      typedef double _mow_angle_offset_deg_type;
      _mow_angle_offset_deg_type mow_angle_offset_deg;
      typedef double _headland_width_type;
      _headland_width_type headland_width;

    PlanningParams():
      outline_passes(0),
      outline_offset(0),
      outline_overlap(0),
      path_spacing(0),
      mow_angle_offset_deg(0),
      headland_width(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        double real;
        uint64_t base;
      } u_outline_passes;
      u_outline_passes.real = this->outline_passes;
      *(outbuffer + offset + 0) = (u_outline_passes.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_outline_passes.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_outline_passes.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_outline_passes.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_outline_passes.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_outline_passes.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_outline_passes.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_outline_passes.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->outline_passes);
      union {
        double real;
        uint64_t base;
      } u_outline_offset;
      u_outline_offset.real = this->outline_offset;
      *(outbuffer + offset + 0) = (u_outline_offset.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_outline_offset.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_outline_offset.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_outline_offset.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_outline_offset.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_outline_offset.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_outline_offset.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_outline_offset.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->outline_offset);
      union {
        double real;
        uint64_t base;
      } u_outline_overlap;
      u_outline_overlap.real = this->outline_overlap;
      *(outbuffer + offset + 0) = (u_outline_overlap.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_outline_overlap.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_outline_overlap.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_outline_overlap.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_outline_overlap.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_outline_overlap.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_outline_overlap.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_outline_overlap.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->outline_overlap);
      union {
        double real;
        uint64_t base;
      } u_path_spacing;
      u_path_spacing.real = this->path_spacing;
      *(outbuffer + offset + 0) = (u_path_spacing.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_path_spacing.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_path_spacing.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_path_spacing.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_path_spacing.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_path_spacing.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_path_spacing.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_path_spacing.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->path_spacing);
      union {
        double real;
        uint64_t base;
      } u_mow_angle_offset_deg;
      u_mow_angle_offset_deg.real = this->mow_angle_offset_deg;
      *(outbuffer + offset + 0) = (u_mow_angle_offset_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_mow_angle_offset_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_mow_angle_offset_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_mow_angle_offset_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_mow_angle_offset_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_mow_angle_offset_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_mow_angle_offset_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_mow_angle_offset_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->mow_angle_offset_deg);
      union {
        double real;
        uint64_t base;
      } u_headland_width;
      u_headland_width.real = this->headland_width;
      *(outbuffer + offset + 0) = (u_headland_width.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_headland_width.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_headland_width.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_headland_width.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_headland_width.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_headland_width.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_headland_width.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_headland_width.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->headland_width);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        double real;
        uint64_t base;
      } u_outline_passes;
      u_outline_passes.base = 0;
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_outline_passes.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->outline_passes = u_outline_passes.real;
      offset += sizeof(this->outline_passes);
      union {
        double real;
        uint64_t base;
      } u_outline_offset;
      u_outline_offset.base = 0;
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_outline_offset.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->outline_offset = u_outline_offset.real;
      offset += sizeof(this->outline_offset);
      union {
        double real;
        uint64_t base;
      } u_outline_overlap;
      u_outline_overlap.base = 0;
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_outline_overlap.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->outline_overlap = u_outline_overlap.real;
      offset += sizeof(this->outline_overlap);
      union {
        double real;
        uint64_t base;
      } u_path_spacing;
      u_path_spacing.base = 0;
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_path_spacing.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->path_spacing = u_path_spacing.real;
      offset += sizeof(this->path_spacing);
      union {
        double real;
        uint64_t base;
      } u_mow_angle_offset_deg;
      u_mow_angle_offset_deg.base = 0;
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_mow_angle_offset_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->mow_angle_offset_deg = u_mow_angle_offset_deg.real;
      offset += sizeof(this->mow_angle_offset_deg);
      union {
        double real;
        uint64_t base;
      } u_headland_width;
      u_headland_width.base = 0;
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_headland_width.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->headland_width = u_headland_width.real;
      offset += sizeof(this->headland_width);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/PlanningParams"; };
    virtual const char * getMD5() override { return "f82478d6e47109725961017e91dce55a"; };

  };

}
#endif
