#ifndef _ROS_mower_msgs_PlanMetadata_h
#define _ROS_mower_msgs_PlanMetadata_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "mowgli_interfaces/Checkpoint.h"

namespace mower_msgs
{

  class PlanMetadata : public ros::Msg
  {
    public:
      typedef double _mow_angle_used_deg_type;
      _mow_angle_used_deg_type mow_angle_used_deg;
      typedef uint32_t _outline_passes_used_type;
      _outline_passes_used_type outline_passes_used;
      typedef double _path_spacing_used_type;
      _path_spacing_used_type path_spacing_used;
      uint32_t processed_area_indices_length;
      typedef uint32_t _processed_area_indices_type;
      _processed_area_indices_type st_processed_area_indices;
      _processed_area_indices_type * processed_area_indices;
      uint32_t skipped_area_indices_length;
      typedef uint32_t _skipped_area_indices_type;
      _skipped_area_indices_type st_skipped_area_indices;
      _skipped_area_indices_type * skipped_area_indices;
      uint32_t skip_reasons_length;
      typedef const char* _skip_reasons_type;
      _skip_reasons_type st_skip_reasons;
      _skip_reasons_type * skip_reasons;
      uint32_t warnings_length;
      typedef const char* _warnings_type;
      _warnings_type st_warnings;
      _warnings_type * warnings;
      typedef mowgli_interfaces::Checkpoint _checkpoint_seed_type;
      _checkpoint_seed_type checkpoint_seed;

    PlanMetadata():
      mow_angle_used_deg(0),
      outline_passes_used(0),
      path_spacing_used(0),
      processed_area_indices_length(0), st_processed_area_indices(), processed_area_indices(nullptr),
      skipped_area_indices_length(0), st_skipped_area_indices(), skipped_area_indices(nullptr),
      skip_reasons_length(0), st_skip_reasons(), skip_reasons(nullptr),
      warnings_length(0), st_warnings(), warnings(nullptr),
      checkpoint_seed()
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      union {
        double real;
        uint64_t base;
      } u_mow_angle_used_deg;
      u_mow_angle_used_deg.real = this->mow_angle_used_deg;
      *(outbuffer + offset + 0) = (u_mow_angle_used_deg.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_mow_angle_used_deg.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_mow_angle_used_deg.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_mow_angle_used_deg.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_mow_angle_used_deg.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_mow_angle_used_deg.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_mow_angle_used_deg.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_mow_angle_used_deg.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->mow_angle_used_deg);
      union {
        uint32_t real;
        uint32_t base;
      } u_outline_passes_used;
      u_outline_passes_used.real = this->outline_passes_used;
      *(outbuffer + offset + 0) = (u_outline_passes_used.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_outline_passes_used.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_outline_passes_used.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_outline_passes_used.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->outline_passes_used);
      union {
        double real;
        uint64_t base;
      } u_path_spacing_used;
      u_path_spacing_used.real = this->path_spacing_used;
      *(outbuffer + offset + 0) = (u_path_spacing_used.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_path_spacing_used.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_path_spacing_used.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_path_spacing_used.base >> (8 * 3)) & 0xFF;
      *(outbuffer + offset + 4) = (u_path_spacing_used.base >> (8 * 4)) & 0xFF;
      *(outbuffer + offset + 5) = (u_path_spacing_used.base >> (8 * 5)) & 0xFF;
      *(outbuffer + offset + 6) = (u_path_spacing_used.base >> (8 * 6)) & 0xFF;
      *(outbuffer + offset + 7) = (u_path_spacing_used.base >> (8 * 7)) & 0xFF;
      offset += sizeof(this->path_spacing_used);
      *(outbuffer + offset + 0) = (this->processed_area_indices_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->processed_area_indices_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->processed_area_indices_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->processed_area_indices_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->processed_area_indices_length);
      for( uint32_t i = 0; i < processed_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_processed_area_indices[i];
        u_processed_area_indices[i].real = this->processed_area_indices[i];
        *(outbuffer + offset + 0) = (u_processed_area_indices[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_processed_area_indices[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_processed_area_indices[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_processed_area_indices[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->processed_area_indices[i]);
      }
      *(outbuffer + offset + 0) = (this->skipped_area_indices_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->skipped_area_indices_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->skipped_area_indices_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->skipped_area_indices_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->skipped_area_indices_length);
      for( uint32_t i = 0; i < skipped_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_skipped_area_indices[i];
        u_skipped_area_indices[i].real = this->skipped_area_indices[i];
        *(outbuffer + offset + 0) = (u_skipped_area_indices[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_skipped_area_indices[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_skipped_area_indices[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_skipped_area_indices[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->skipped_area_indices[i]);
      }
      *(outbuffer + offset + 0) = (this->skip_reasons_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->skip_reasons_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->skip_reasons_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->skip_reasons_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->skip_reasons_length);
      for( uint32_t i = 0; i < skip_reasons_length; i++){
        uint32_t length_skip_reasons[i] = strlen(this->skip_reasons[i]);
        varToArr(outbuffer + offset, length_skip_reasons[i]);
        offset += 4;
        memcpy(outbuffer + offset, this->skip_reasons[i], length_skip_reasons[i]);
        offset += length_skip_reasons[i];
      }
      *(outbuffer + offset + 0) = (this->warnings_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->warnings_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->warnings_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->warnings_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->warnings_length);
      for( uint32_t i = 0; i < warnings_length; i++){
        uint32_t length_warnings[i] = strlen(this->warnings[i]);
        varToArr(outbuffer + offset, length_warnings[i]);
        offset += 4;
        memcpy(outbuffer + offset, this->warnings[i], length_warnings[i]);
        offset += length_warnings[i];
      }
      offset += this->checkpoint_seed.serialize(outbuffer + offset);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      union {
        double real;
        uint64_t base;
      } u_mow_angle_used_deg;
      u_mow_angle_used_deg.base = 0;
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_mow_angle_used_deg.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->mow_angle_used_deg = u_mow_angle_used_deg.real;
      offset += sizeof(this->mow_angle_used_deg);
      union {
        uint32_t real;
        uint32_t base;
      } u_outline_passes_used;
      u_outline_passes_used.base = 0;
      u_outline_passes_used.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_outline_passes_used.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_outline_passes_used.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_outline_passes_used.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->outline_passes_used = u_outline_passes_used.real;
      offset += sizeof(this->outline_passes_used);
      union {
        double real;
        uint64_t base;
      } u_path_spacing_used;
      u_path_spacing_used.base = 0;
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 3))) << (8 * 3);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 4))) << (8 * 4);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 5))) << (8 * 5);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 6))) << (8 * 6);
      u_path_spacing_used.base |= ((uint64_t) (*(inbuffer + offset + 7))) << (8 * 7);
      this->path_spacing_used = u_path_spacing_used.real;
      offset += sizeof(this->path_spacing_used);
      uint32_t processed_area_indices_lengthT = ((uint32_t) (*(inbuffer + offset)));
      processed_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      processed_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      processed_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->processed_area_indices_length);
      if(processed_area_indices_lengthT > processed_area_indices_length)
        this->processed_area_indices = (uint32_t*)realloc(this->processed_area_indices, processed_area_indices_lengthT * sizeof(uint32_t));
      processed_area_indices_length = processed_area_indices_lengthT;
      for( uint32_t i = 0; i < processed_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_processed_area_indices[i];
        u_processed_area_indices[i].base = 0;
        u_processed_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_processed_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_processed_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_processed_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->processed_area_indices[i] = u_processed_area_indices[i].real;
        offset += sizeof(this->processed_area_indices[i]);
      }
      uint32_t skipped_area_indices_lengthT = ((uint32_t) (*(inbuffer + offset)));
      skipped_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      skipped_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      skipped_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->skipped_area_indices_length);
      if(skipped_area_indices_lengthT > skipped_area_indices_length)
        this->skipped_area_indices = (uint32_t*)realloc(this->skipped_area_indices, skipped_area_indices_lengthT * sizeof(uint32_t));
      skipped_area_indices_length = skipped_area_indices_lengthT;
      for( uint32_t i = 0; i < skipped_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_skipped_area_indices[i];
        u_skipped_area_indices[i].base = 0;
        u_skipped_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_skipped_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_skipped_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_skipped_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->skipped_area_indices[i] = u_skipped_area_indices[i].real;
        offset += sizeof(this->skipped_area_indices[i]);
      }
      uint32_t skip_reasons_lengthT = ((uint32_t) (*(inbuffer + offset)));
      skip_reasons_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      skip_reasons_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      skip_reasons_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->skip_reasons_length);
      if(skip_reasons_lengthT > skip_reasons_length)
        this->skip_reasons = (const char**)realloc(this->skip_reasons, skip_reasons_lengthT * sizeof(const char*));
      skip_reasons_length = skip_reasons_lengthT;
      for( uint32_t i = 0; i < skip_reasons_length; i++){
        uint32_t length_skip_reasons[i];
        arrToVar(length_skip_reasons[i], (inbuffer + offset));
        offset += 4;
        for(unsigned int k= offset; k< offset+length_skip_reasons[i]; ++k){
            inbuffer[k-1]=inbuffer[k];
        }
        inbuffer[offset+length_skip_reasons[i]-1]=0;
        this->skip_reasons[i] = (char *)(inbuffer + offset-1);
        offset += length_skip_reasons[i];
      }
      uint32_t warnings_lengthT = ((uint32_t) (*(inbuffer + offset)));
      warnings_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      warnings_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      warnings_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->warnings_length);
      if(warnings_lengthT > warnings_length)
        this->warnings = (const char**)realloc(this->warnings, warnings_lengthT * sizeof(const char*));
      warnings_length = warnings_lengthT;
      for( uint32_t i = 0; i < warnings_length; i++){
        uint32_t length_warnings[i];
        arrToVar(length_warnings[i], (inbuffer + offset));
        offset += 4;
        for(unsigned int k= offset; k< offset+length_warnings[i]; ++k){
            inbuffer[k-1]=inbuffer[k];
        }
        inbuffer[offset+length_warnings[i]-1]=0;
        this->warnings[i] = (char *)(inbuffer + offset-1);
        offset += length_warnings[i];
      }
      offset += this->checkpoint_seed.deserialize(inbuffer + offset);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/PlanMetadata"; };
    virtual const char * getMD5() override { return "4a0eade5632cfee4b5c98589b482ce59"; };

  };

}
#endif
