#ifndef _ROS_mower_msgs_PlanError_h
#define _ROS_mower_msgs_PlanError_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "geometry_msgs/Polygon.h"

namespace mower_msgs
{

  class PlanError : public ros::Msg
  {
    public:
      typedef uint8_t _error_code_type;
      _error_code_type error_code;
      typedef uint8_t _failed_validation_point_type;
      _failed_validation_point_type failed_validation_point;
      uint32_t affected_area_indices_length;
      typedef uint32_t _affected_area_indices_type;
      _affected_area_indices_type st_affected_area_indices;
      _affected_area_indices_type * affected_area_indices;
      uint32_t affected_polygons_length;
      typedef geometry_msgs::Polygon _affected_polygons_type;
      _affected_polygons_type st_affected_polygons;
      _affected_polygons_type * affected_polygons;
      typedef const char* _human_readable_type;
      _human_readable_type human_readable;
      enum { ERROR_NO_AREAS = 1 };
      enum { ERROR_AREA_TOO_NARROW = 2 };
      enum { ERROR_OBSTACLE_BLOCKS_AREA = 3 };
      enum { ERROR_DOCK_OUTSIDE_AREAS = 4 };
      enum { ERROR_FOOTPRINT_VIOLATION = 5 };
      enum { ERROR_OBSTACLE_OFFSET_FAILED = 6 };
      enum { ERROR_RESUME_CHECKPOINT_INVALID = 7 };
      enum { ERROR_INTERNAL = 255 };

    PlanError():
      error_code(0),
      failed_validation_point(0),
      affected_area_indices_length(0), st_affected_area_indices(), affected_area_indices(nullptr),
      affected_polygons_length(0), st_affected_polygons(), affected_polygons(nullptr),
      human_readable("")
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      *(outbuffer + offset + 0) = (this->error_code >> (8 * 0)) & 0xFF;
      offset += sizeof(this->error_code);
      *(outbuffer + offset + 0) = (this->failed_validation_point >> (8 * 0)) & 0xFF;
      offset += sizeof(this->failed_validation_point);
      *(outbuffer + offset + 0) = (this->affected_area_indices_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->affected_area_indices_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->affected_area_indices_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->affected_area_indices_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->affected_area_indices_length);
      for( uint32_t i = 0; i < affected_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_affected_area_indices[i];
        u_affected_area_indices[i].real = this->affected_area_indices[i];
        *(outbuffer + offset + 0) = (u_affected_area_indices[i].base >> (8 * 0)) & 0xFF;
        *(outbuffer + offset + 1) = (u_affected_area_indices[i].base >> (8 * 1)) & 0xFF;
        *(outbuffer + offset + 2) = (u_affected_area_indices[i].base >> (8 * 2)) & 0xFF;
        *(outbuffer + offset + 3) = (u_affected_area_indices[i].base >> (8 * 3)) & 0xFF;
        offset += sizeof(this->affected_area_indices[i]);
      }
      *(outbuffer + offset + 0) = (this->affected_polygons_length >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (this->affected_polygons_length >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (this->affected_polygons_length >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (this->affected_polygons_length >> (8 * 3)) & 0xFF;
      offset += sizeof(this->affected_polygons_length);
      for( uint32_t i = 0; i < affected_polygons_length; i++){
        offset += this->affected_polygons[i].serialize(outbuffer + offset);
      }
      uint32_t length_human_readable = strlen(this->human_readable);
      varToArr(outbuffer + offset, length_human_readable);
      offset += 4;
      memcpy(outbuffer + offset, this->human_readable, length_human_readable);
      offset += length_human_readable;
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      this->error_code =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->error_code);
      this->failed_validation_point =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->failed_validation_point);
      uint32_t affected_area_indices_lengthT = ((uint32_t) (*(inbuffer + offset)));
      affected_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      affected_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      affected_area_indices_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->affected_area_indices_length);
      if(affected_area_indices_lengthT > affected_area_indices_length)
        this->affected_area_indices = (uint32_t*)realloc(this->affected_area_indices, affected_area_indices_lengthT * sizeof(uint32_t));
      affected_area_indices_length = affected_area_indices_lengthT;
      for( uint32_t i = 0; i < affected_area_indices_length; i++){
        union {
          uint32_t real;
          uint32_t base;
        } u_affected_area_indices[i];
        u_affected_area_indices[i].base = 0;
        u_affected_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
        u_affected_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
        u_affected_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
        u_affected_area_indices[i].base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
        this->affected_area_indices[i] = u_affected_area_indices[i].real;
        offset += sizeof(this->affected_area_indices[i]);
      }
      uint32_t affected_polygons_lengthT = ((uint32_t) (*(inbuffer + offset)));
      affected_polygons_lengthT |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      affected_polygons_lengthT |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      affected_polygons_lengthT |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      offset += sizeof(this->affected_polygons_length);
      if(affected_polygons_lengthT > affected_polygons_length)
        this->affected_polygons = (geometry_msgs::Polygon*)realloc(this->affected_polygons, affected_polygons_lengthT * sizeof(geometry_msgs::Polygon));
      affected_polygons_length = affected_polygons_lengthT;
      for( uint32_t i = 0; i < affected_polygons_length; i++){
        offset += this->affected_polygons[i].deserialize(inbuffer + offset);
      }
      uint32_t length_human_readable;
      arrToVar(length_human_readable, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_human_readable; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_human_readable-1]=0;
      this->human_readable = (char *)(inbuffer + offset-1);
      offset += length_human_readable;
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/PlanError"; };
    virtual const char * getMD5() override { return "791b253e62f65aff13176dde7b0c678f"; };

  };

}
#endif
