// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
	"github.com/cedbossneo/mowglinext/pkg/msgs/nav"
)

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
	JobId                     string                         `json:"job_id"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetAllAreasReq for mowgli_interfaces/srv/GetAllAreas request (empty).
type GetAllAreasReq struct{}

// GetAllAreasRes for mowgli_interfaces/srv/GetAllAreas response.
type GetAllAreasRes struct {
	Areas                     []MapArea                      `json:"areas"`
}

// GetCoverageStatusReq for mowgli_interfaces/srv/GetCoverageStatus request.
type GetCoverageStatusReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
}

// GetCoverageStatusRes for mowgli_interfaces/srv/GetCoverageStatus response.
type GetCoverageStatusRes struct {
	Success                   bool                           `json:"success"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	TotalCells                uint32                         `json:"total_cells"`
	MowedCells                uint32                         `json:"mowed_cells"`
	ObstacleCells             uint32                         `json:"obstacle_cells"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetNextStripReq for mowgli_interfaces/srv/GetNextStrip request.
type GetNextStripReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	RobotX                    float64                        `json:"robot_x"`
	RobotY                    float64                        `json:"robot_y"`
	PreferHeadland            bool                           `json:"prefer_headland"`
}

// GetNextStripRes for mowgli_interfaces/srv/GetNextStrip response.
type GetNextStripRes struct {
	Success                   bool                           `json:"success"`
	CoverageComplete          bool                           `json:"coverage_complete"`
	StripPath                 nav.Path                       `json:"strip_path"`
	TransitGoal               geometry.PoseStamped           `json:"transit_goal"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
	Phase                     string                         `json:"phase"`
}

// GetOutlinePathReq for mowgli_interfaces/srv/GetOutlinePath request.
type GetOutlinePathReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	InsetM                    float32                        `json:"inset_m"`
}

// GetOutlinePathRes for mowgli_interfaces/srv/GetOutlinePath response.
type GetOutlinePathRes struct {
	Success                   bool                           `json:"success"`
	ErrorMessage              string                         `json:"error_message"`
	OutlinePath               nav.Path                       `json:"outline_path"`
	EffectiveInsetM           float32                        `json:"effective_inset_m"`
	NumVertices               uint32                         `json:"num_vertices"`
}

// GetRecoveryPointReq for mowgli_interfaces/srv/GetRecoveryPoint request (empty).
type GetRecoveryPointReq struct{}

// GetRecoveryPointRes for mowgli_interfaces/srv/GetRecoveryPoint response.
type GetRecoveryPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	RecoveryPose              geometry.Pose                  `json:"recovery_pose"`
	DistanceOutside           float64                        `json:"distance_outside"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// PreviewPlanReq for mowgli_interfaces/srv/PreviewPlan request.
type PreviewPlanReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
}

// PreviewPlanRes for mowgli_interfaces/srv/PreviewPlan response.
type PreviewPlanRes struct {
	Success                   bool                           `json:"success"`
	ErrorMessage              string                         `json:"error_message"`
	StripPlan                 nav.Path                       `json:"strip_plan"`
	SegmentStarts             []uint32                       `json:"segment_starts"`
	OutlinePath               nav.Path                       `json:"outline_path"`
	OutlineInsetM             float32                        `json:"outline_inset_m"`
	NumStrips                 uint32                         `json:"num_strips"`
	PolygonDiagM              float32                        `json:"polygon_diag_m"`
	EffectiveInsetM           float32                        `json:"effective_inset_m"`
	MowAngleDeg               float32                        `json:"mow_angle_deg"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
}

// SetPlanningParamsReq for mowgli_interfaces/srv/SetPlanningParams request.
type SetPlanningParamsReq struct {
	OutlinePasses             float64                        `json:"outline_passes"`
	OutlineOffset             float64                        `json:"outline_offset"`
	OutlineOverlap            float64                        `json:"outline_overlap"`
	PathSpacing               float64                        `json:"path_spacing"`
	MowAngleOffsetDeg         float64                        `json:"mow_angle_offset_deg"`
	HeadlandWidth             float64                        `json:"headland_width"`
}

// SetPlanningParamsRes for mowgli_interfaces/srv/SetPlanningParams response.
type SetPlanningParamsRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// WriteCheckpointReq for mowgli_interfaces/srv/WriteCheckpoint request.
type WriteCheckpointReq struct {
	Checkpoint                Checkpoint                     `json:"checkpoint"`
}

// WriteCheckpointRes for mowgli_interfaces/srv/WriteCheckpoint response.
type WriteCheckpointRes struct {
	Success                   bool                           `json:"success"`
	ErrorMessage              string                         `json:"error_message"`
}

