// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
)

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
	JobId                     string                         `json:"job_id"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetAllAreasReq for mowgli_interfaces/srv/GetAllAreas request (empty).
type GetAllAreasReq struct{}

// GetAllAreasRes for mowgli_interfaces/srv/GetAllAreas response.
type GetAllAreasRes struct {
	Areas                     []MapArea                      `json:"areas"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetRecoveryPointReq for mowgli_interfaces/srv/GetRecoveryPoint request (empty).
type GetRecoveryPointReq struct{}

// GetRecoveryPointRes for mowgli_interfaces/srv/GetRecoveryPoint response.
type GetRecoveryPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	RecoveryPose              geometry.Pose                  `json:"recovery_pose"`
	DistanceOutside           float64                        `json:"distance_outside"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
}

// SetPlanningParamsReq for mowgli_interfaces/srv/SetPlanningParams request.
type SetPlanningParamsReq struct {
	OutlinePasses             float64                        `json:"outline_passes"`
	OutlineOffset             float64                        `json:"outline_offset"`
	OutlineOverlap            float64                        `json:"outline_overlap"`
	PathSpacing               float64                        `json:"path_spacing"`
	MowAngleOffsetDeg         float64                        `json:"mow_angle_offset_deg"`
	HeadlandWidth             float64                        `json:"headland_width"`
}

// SetPlanningParamsRes for mowgli_interfaces/srv/SetPlanningParams response.
type SetPlanningParamsRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// WriteCheckpointReq for mowgli_interfaces/srv/WriteCheckpoint request.
type WriteCheckpointReq struct {
	Checkpoint                Checkpoint                     `json:"checkpoint"`
}

// WriteCheckpointRes for mowgli_interfaces/srv/WriteCheckpoint response.
type WriteCheckpointRes struct {
	Success                   bool                           `json:"success"`
	ErrorMessage              string                         `json:"error_message"`
}

